### ISSUE TITLE
Add better messages, mention type it can be rewritten as

### ISSUE THREAD

**Issue by GideonBear** [TylerYep/flake8-future-annotations#10]
For example, instead of `FA100 Missing from __future__ import annotations but imports: Tuple` it could be something like ``FA100 Missing from __future__ import annotations but imports: `Tuple`; use `tuple` instead.``
`SIMPLIFIABLE_TYPES` could be a dict, where the values are the replacements.

If needed I can make a PR for this

**Comment by TylerYep** [comment]
Similarly to #8, some uses of uppercase Tuple are valid and it would be misleading to tell the user the use `tuple` instead. I'll add a note in the README clarifying this.
