### ISSUE TITLE
Support allowlisting some types?

### ISSUE THREAD

**Issue by PeterJCLaw** [TylerYep/flake8-future-annotations#12]
Thanks for this handy extension. It's really useful as a mechanism to migrate towards newer style types.

However, sometimes I want to keep some of the older style types where they help clarify the code. The example I most often have is `typing.Union`, which I want to keep as it offers a more obvious wrapping strategy.

Consider:
``` python
SomeAlias = VeryLongNameOne | VeryLongNameTwo[Thing] | dict[tuple[str, int], list[str] | tuple[str, ...]] | VeryLongNameThree
```
versus
``` python
SomeAlias = (
    VeryLongNameOne |
    VeryLongNameTwo[Thing] |
    dict[tuple[str, int], list[str] | tuple[str, ...]] |
    VeryLongNameThree
)
```
Here, for visual balance and to reduce diff noise, I'd prefer to repeat the separator after the last element in the collection too, which means I tend to instead do:
``` python
SomeAlias = Union[
    VeryLongNameOne,
    VeryLongNameTwo[Thing],
    dict[tuple[str, int], list[str] | tuple[str, ...]],
    VeryLongNameThree,
]
```

While I generally prefer the pipe style, there are enough occasions (especially in older code) where I have complex unions that need wrapping due to their length or are just clearer in the wrapped format using `Union` explicitly.

It would be great if this extension could be configured to allow (i.e: ignore imports of) specific types, so that it can be used in conjunction with local code styles such as this.

**Comment by PeterJCLaw** [comment]
> I personally think that the version without Union is more consistent

For the non-wrapped case I definitely agree that the pipe syntax is clearer. I would only use `Union` in the wrapped form.

> the diff noise or visual improvement would be minimal after using ruff or pyupgrade+black.

Regarding diff noise -- this isn't really about black/ruff/etc. -- each of these code snippets is consistent with those tools (modulo line length). As long as you have trailing commas in place (per e.g: `flake8-commas` or `add-trailing-comma`) there's an option to avoid diff noise completely.

For clarity on what I mean about the diff noise -- I mean that when adding an element to each of these unions the diff would be like:

```diff
-SomeAlias = VeryLongNameOne | VeryLongNameTwo[Thing] | dict[tuple[str, int], list[str] | tuple[str, ...]]
+SomeAlias = VeryLongNameOne | VeryLongNameTwo[Thing] | dict[tuple[str, int], list[str] | tuple[str, ...]] | VeryLongNameThree
```
Here, a simple line-based diff indicates the whole line has changed, which is essentially right but not particularity usefully so.

versus

```diff
 SomeAlias = (
     VeryLongNameOne |
     VeryLongNameTwo[Thing] |
-    dict[tuple[str, int], list[str] | tuple[str, ...]]
+    dict[tuple[str, int], list[str] | tuple[str, ...]] |
+    VeryLongNameThree
 )
```
Here the diff indicates that the `dict[...]` line has changed. While technically correct from a text perspective, it is misleading when considering the semantics -- this is what I mean by noise.

versus

``` diff
 SomeAlias = Union[
     VeryLongNameOne,
     VeryLongNameTwo[Thing],
     dict[tuple[str, int], list[str] | tuple[str, ...]],
+    VeryLongNameThree,
 ]
```
This option (my preference for long unions) avoids the noise associated with changing unrelated lines.

Obviously swapping between each of these styles would come with a different diff, however that's inherently unavoidable and I'd consider it a separate thing.

> If you really want to keep the Union, I recommend adding a `# noqa: FA100`

Yeah, I'd considered this. However this unfortunately (obviously) means that I don't get checking for any of the other types, which is a significant drawback. If the errors were associated with the usages of the various types then that might be an option, however I suspect that would be quite noisy per file and perhaps more effort overall to maintain.

---
Thanks for considering this. I'm probably going to stick with using [`flake8-modern-annotations`](https://pypi.org/project/flake8-modern-annotations/) on its own and just using this linter as part of migrating codebases (rather than ongoing).

**Comment by TylerYep** [comment]
That was my understanding of diff noise as well, I just think the 1 line vs 2 lines change for the pipe syntax is not significant effort for a reviewer and worth building additional configurability around.

I haven't seen `flake8-modern-annotations` before, thanks for the link! It definitely looks more configurable and will probably suit your specific needs better. 👍
