### ISSUE TITLE
Add option to exclude `Optional`

### ISSUE THREAD

**Issue by nyuszika7h** [TylerYep/flake8-future-annotations#4]
Please add an option to not complain about `from typing import Optional`. I prefer `Optional[X]` over `X | None`, I consider the latter bad style.

**Comment by TylerYep** [comment]
Why do you consider Optional bad style? It's hard to add to existing annotations and takes more characters than adding `| None`

**Comment by nyuszika7h** [comment]
One of the reasons I dislike it is because it looks repetitive when you do `foo: str | None = None`, and `foo: None | str = None` isn't much better either (if using the union syntax I would rather put `None` at the end because the more important info is what type it should be if it is present IMO).

Anyway, it's subjective, and the PEP does not deprecate the old syntax, it merely mentions that another way is possible now. Some people might like it because it's shorter, but IMO `Optional` is much less awkward readability-wise.

I think it would make sense to either split it out into another error code or add an option to control this separately. I don't think this really counts as feature creep but if you don't feel like there's a compelling enough reason to add this I can just continue using my fork.

**Comment by TylerYep** [comment]
Agree to disagree here, I don't want to support this feature, sorry :(

I also think there are Python plans to deprecate Optional, Union from the typing module, which I strongly support.

Thank you for the discussion!

**Comment by nyuszika7h** [comment]
I wouldn't necessarily jump to that conclusion so quickly. Note how there's a distinction between `typing.List` and friends saying "Deprecated", while `typing.Optional` merely says "Changed", suggesting that an alternative syntax is possible. So if they do deprecate it in the future, there would probably be plenty of notice period.

Either way, this seems to be a widespread trend so I don't blame you for following it. It's trivial to maintain my own fork with a one-line change anyway (since it's a personal fork mainly intended to be used by myself I don't even have to bother keeping the current behavior as an option).

I just hope they don't remove `Optional` until/unless they add `X?` optional syntax (but that discussion has nothing to do with this repo anymore, I'm just thinking out loud).
