### ISSUE TITLE
Considering moving flake8 plugin under pycqa?

### ISSUE THREAD

**Issue by ssbarnea** [TylerYep/flake8-future-annotations#6]
I wonder WDYT about moving this plugin under https://github.com/PyCQA in order to ensure its future. Same measure was taken by other plugin based tools like tox, pytest and sphinx.

I ask this because while I like the extension, I feel anxious about adding a build time dependency on a tool that depends on a single individual.

**Comment by TylerYep** [comment]
HI @ssbarnea, I would be open to moving this plugin to the PyCQA org. Could you explain what the process to do so looks like?

**Comment by ssbarnea** [comment]
Create a ticket under https://github.com/PyCQA/meta/issues where you state that as the author of this plugin you would like to move it under pycqa so it would be closer to flake8 and make it easier for others to contribute to it. I will back your proposal and hopefully it will be accepted. I have under them doc8 project.

In case it gets rejected, i have two other options we can take, both of them with enough python people that can give a hand if needed.

**Comment by TylerYep** [comment]
With the rise of Ruff and the inclusion of this flake8 rule already, I don't think ownership of this plugin needs to change anymore. To a faster future!
