### ISSUE TITLE
Add `Self` to `SIMPLIFIABLE_TYPES`

### ISSUE THREAD

**Issue by GideonBear** [TylerYep/flake8-future-annotations#7]
Example:
```py
from typing import Self

class Test:
    def func(self) -> Self:
        ...
```
Can be rewritten as:
```py
from __future__ import annotations

class Test:
    def func(self) -> Test:
        ...
```

**Comment by GideonBear** [comment]
> I actually think Self is more correct than Test in some cases?

Can you show an example? IMO, `Test` is always clearer than `Self`.
If I make a class that inherits from `Test` and return `cls()`, `Test` is still correct (as it inherits from it).

**Comment by TylerYep** [comment]
https://peps.python.org/pep-0673/

**Comment by GideonBear** [comment]
> https://peps.python.org/pep-0673/

You're right, sorry, I should've done more research into what the actual goal of the type was.
