### ISSUE TITLE
Error with type aliases (assignment) in python<3.10

### ISSUE THREAD

**Issue by GideonBear** [TylerYep/flake8-future-annotations#8]
Input file:
```py
A = Union[str, int]
B = Tuple[str]
```
`flake8-future-annotations` suggests `FA100 Missing from __future__ import annotations but imports: Union, Tuple`
But when using `from __future__ import annotations` this is the result:
```py
from __future__ import annotations

A = str | int
B = tuple[str]
```
Both assignments will fail at runtime in python<3.10 (as they aren't postponed like with type hints)

**Comment by TylerYep** [comment]
Yes, this is the correct behavior. Code before 3.10 cannot always be converted, however the long time is telling the user to do something more subtle.

```
From __future__ import annotations
From typing import Tuple, Union

A = Union[str, int]
B = Tuple[str]
C: list[int] =  [3]
```

This will pass lint checks and work correctly.
Pyupgrade will now update C but now lines A or B.

**Comment by GideonBear** [comment]
> Yes, this is the correct behavior. Code before 3.10 cannot always be converted, however the lint check is telling the user to do something more subtle.
> 
> ```
> from __future__ import annotations
> from typing import Tuple, Union
> 
> A = Union[str, int]
> B = Tuple[str]
> C: list[int] =  [3]
> ```
> 
> This will pass lint checks and work correctly. Pyupgrade will now update C but now lines A or B.

Ah, that makes sense. Maybe this should be included in the documentation (README.md)?

**Comment by GideonBear** [comment]
I just realized, you don't even need to keep the `Tuple, Union` imports, you can put the type aliases in an `if TYPE_CHECKING:` block. I think that should be mentioned instead of keeping them and adding `from __future__ import annotations`.

**Comment by TylerYep** [comment]
You do need to keep the imports in cases like Python 3.7:

```
a = ["hi"]
x = cast(List[Union[int, str]], a)
```

**Comment by GideonBear** [comment]
> You do need to keep the imports in cases like Python 3.7:
> 
> ```
> a = ["hi"]
> x = cast(List[Union[int, str]], a)
> ```

Yes, for casting it's needed, but casting isn't that common (at least I don't use it) and then you can still keep the imports, but for type aliases you can put them in an `if TYPE_CHECKING` block. And as the plugin enforces using `from __future__ import annotations`, an `if TYPE_CHECKING` block is a good solution for it.

**Comment by TylerYep** [comment]
Casting is fairly common in coffee that I've read. In any case, if the solution doesn't cover all cases it's not worth pursuing imo
